import { FileText } from "lucide-react";
import { SectionPreview } from "@/components/section-preview";

export default function ExecutiveDigestPage() {
  return (
    <SectionPreview
      icon={FileText}
      title="Executive Digest"
      description="A daily, auto-generated summary of engineering health — written for a five-minute read, not a dashboard deep-dive."
      bullets={[
    "Auto-generated by EnsembleAI from the day's runs, evals, and incidents",
    "Highlights what changed, not just what's stable",
    "Archived daily so trends are easy to spot",
      ]}
    />
  );
}
